apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: daemonset01
  name: daemonsetdemo
  namespace: myns01
spec:
  selector:
    matchLabels:
      app: nosql
  template:
    metadata:
      labels:
        app: nosql
    spec:
      containers:
        - image: redis:5
          imagePullPolicy: IfNotPresent
          name: redisdb
