apiVersion: v1
kind: Pod
metadata:
  name: first-Pod
  namespace: myspace
  labels:
    app: test
spec:
  containers:
    - name: c1
      ports:
        - containerPort: 80
          name: httpdport80
      image: nginx
      imagePullPolicy: IfNotPresent