apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvdb
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  PersistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /k8sstorage/dbdata
    server: 192.168.122.1