apiVersion: v1
kind: Pod
metadata:
  name: hostport
  labels:
    name: net
spec:
  containers:
    - image: nginx:1.16
      name: hostport
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          hostPort: 8080