apiVersion: v1
kind: Pod
metadata:
  name: hostnetwork
  labels:
    name: net
spec:
  hostNetwork: true
  containers:
    - image: nginx:1.16
      name: hostnetwork
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80